title:               Roxanne Shirazi
url:                 https://rshirazi.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: true

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Roxanne Shirazi
  url:               roxanneshirazi.com
  email:             rshirazi@gc.cuny.edu

collections:
  projects:
    output: true
    permalink: /:collection/:path/
  topics:
    output: true 
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

teaser: /assets/images/logo.png   

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist